name: inventory_manager
description: Inventory management app with Firestore and Provider.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  uuid: ^4.2.1
  intl: ^0.19.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
